version: 2
jobs:
  toxify:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: Install libmagic
          command: sudo apt-get install libmagic
      - run: pip install tox && tox
workflows:
  version: 2